/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_STAR = 2,
  aux_sym_bold_token1 = 3,
  anon_sym_SLASH = 4,
  aux_sym_italic_token1 = 5,
  anon_sym__ = 6,
  aux_sym_underline_token1 = 7,
  anon_sym_TILDE = 8,
  aux_sym_code_token1 = 9,
  anon_sym_EQ = 10,
  aux_sym_verbatim_token1 = 11,
  anon_sym_PLUS = 12,
  aux_sym_strike_through_token1 = 13,
  anon_sym_LBRACK = 14,
  aux_sym_statistics_cookie_token1 = 15,
  anon_sym_PERCENT = 16,
  anon_sym_RBRACK = 17,
  anon_sym_AT_AT = 18,
  aux_sym_export_snippet_token1 = 19,
  aux_sym_export_snippet_token2 = 20,
  anon_sym_LT_LT = 21,
  aux_sym_target_token1 = 22,
  anon_sym_GT_GT = 23,
  anon_sym_LT_LT_LT = 24,
  anon_sym_GT_GT_GT = 25,
  anon_sym_LBRACK_LBRACK = 26,
  aux_sym_regular_link_token1 = 27,
  anon_sym_RBRACK_LBRACK = 28,
  anon_sym_RBRACK_RBRACK = 29,
  sym_plain_link = 30,
  anon_sym_LT = 31,
  aux_sym_angle_link_token1 = 32,
  aux_sym_angle_link_token2 = 33,
  anon_sym_GT = 34,
  anon_sym_BSLASH = 35,
  aux_sym_entity_token1 = 36,
  anon_sym_LBRACE_RBRACE = 37,
  aux_sym_plain_text_token1 = 38,
  sym_TAGS = 39,
  sym_inline = 40,
  sym_title_with_tags = 41,
  sym_title_only = 42,
  sym_title = 43,
  sym_text_markup = 44,
  sym_bold = 45,
  sym_italic = 46,
  sym_underline = 47,
  sym_code = 48,
  sym_verbatim = 49,
  sym_strike_through = 50,
  sym_statistics_cookie = 51,
  sym_export_snippet = 52,
  sym_target = 53,
  sym_radio_target = 54,
  sym_regular_link = 55,
  sym_angle_link = 56,
  sym_entity = 57,
  sym_plain_text = 58,
  aux_sym_title_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [aux_sym_bold_token1] = "bold_token1",
  [anon_sym_SLASH] = "/",
  [aux_sym_italic_token1] = "italic_token1",
  [anon_sym__] = "_",
  [aux_sym_underline_token1] = "underline_token1",
  [anon_sym_TILDE] = "~",
  [aux_sym_code_token1] = "code_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_verbatim_token1] = "verbatim_token1",
  [anon_sym_PLUS] = "+",
  [aux_sym_strike_through_token1] = "strike_through_token1",
  [anon_sym_LBRACK] = "[",
  [aux_sym_statistics_cookie_token1] = "statistics_cookie_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT_AT] = "@@",
  [aux_sym_export_snippet_token1] = "export_snippet_token1",
  [aux_sym_export_snippet_token2] = "export_snippet_token2",
  [anon_sym_LT_LT] = "<<",
  [aux_sym_target_token1] = "target_token1",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT_LT] = "<<<",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [aux_sym_regular_link_token1] = "regular_link_token1",
  [anon_sym_RBRACK_LBRACK] = "][",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_plain_link] = "plain_link",
  [anon_sym_LT] = "<",
  [aux_sym_angle_link_token1] = "angle_link_token1",
  [aux_sym_angle_link_token2] = "angle_link_token2",
  [anon_sym_GT] = ">",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_entity_token1] = "entity_token1",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [aux_sym_plain_text_token1] = "plain_text_token1",
  [sym_TAGS] = "tags",
  [sym_inline] = "inline",
  [sym_title_with_tags] = "title_with_tags",
  [sym_title_only] = "title_only",
  [sym_title] = "title",
  [sym_text_markup] = "text_markup",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_underline] = "underline",
  [sym_code] = "code",
  [sym_verbatim] = "verbatim",
  [sym_strike_through] = "strike_through",
  [sym_statistics_cookie] = "statistics_cookie",
  [sym_export_snippet] = "export_snippet",
  [sym_target] = "target",
  [sym_radio_target] = "radio_target",
  [sym_regular_link] = "regular_link",
  [sym_angle_link] = "angle_link",
  [sym_entity] = "entity",
  [sym_plain_text] = "plain_text",
  [aux_sym_title_repeat1] = "title_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_bold_token1] = aux_sym_bold_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym_italic_token1] = aux_sym_italic_token1,
  [anon_sym__] = anon_sym__,
  [aux_sym_underline_token1] = aux_sym_underline_token1,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_verbatim_token1] = aux_sym_verbatim_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_strike_through_token1] = aux_sym_strike_through_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_statistics_cookie_token1] = aux_sym_statistics_cookie_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT_AT] = anon_sym_AT_AT,
  [aux_sym_export_snippet_token1] = aux_sym_export_snippet_token1,
  [aux_sym_export_snippet_token2] = aux_sym_export_snippet_token2,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT_LT] = anon_sym_LT_LT_LT,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [aux_sym_regular_link_token1] = aux_sym_regular_link_token1,
  [anon_sym_RBRACK_LBRACK] = anon_sym_RBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_plain_link] = sym_plain_link,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_angle_link_token1] = aux_sym_angle_link_token1,
  [aux_sym_angle_link_token2] = aux_sym_angle_link_token2,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_entity_token1] = aux_sym_entity_token1,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [aux_sym_plain_text_token1] = aux_sym_plain_text_token1,
  [sym_TAGS] = sym_TAGS,
  [sym_inline] = sym_inline,
  [sym_title_with_tags] = sym_title_with_tags,
  [sym_title_only] = sym_title_only,
  [sym_title] = sym_title,
  [sym_text_markup] = sym_text_markup,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_underline] = sym_underline,
  [sym_code] = sym_code,
  [sym_verbatim] = sym_verbatim,
  [sym_strike_through] = sym_strike_through,
  [sym_statistics_cookie] = sym_statistics_cookie,
  [sym_export_snippet] = sym_export_snippet,
  [sym_target] = sym_target,
  [sym_radio_target] = sym_radio_target,
  [sym_regular_link] = sym_regular_link,
  [sym_angle_link] = sym_angle_link,
  [sym_entity] = sym_entity,
  [sym_plain_text] = sym_plain_text,
  [aux_sym_title_repeat1] = aux_sym_title_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bold_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_italic_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_underline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_verbatim_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_strike_through_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_statistics_cookie_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_export_snippet_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_export_snippet_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_regular_link_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_plain_link] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_angle_link_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_angle_link_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_entity_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_plain_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_TAGS] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_title_with_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_title_only] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_text_markup] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_strike_through] = {
    .visible = true,
    .named = true,
  },
  [sym_statistics_cookie] = {
    .visible = true,
    .named = true,
  },
  [sym_export_snippet] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_radio_target] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_link] = {
    .visible = true,
    .named = true,
  },
  [sym_angle_link] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_tags = 1,
  field_title = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_tags] = "tags",
  [field_title] = "title",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tags, 0},
  [1] =
    {field_title, 0},
  [2] =
    {field_tags, 1},
    {field_title, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
};

static const TSCharacterRange aux_sym_plain_text_token1_character_set_1[] = {
  {0, '\t'}, {0x0b, ')'}, {',', '.'}, {'0', '9'}, {';', ';'}, {'?', '?'}, {'A', 'Z'}, {'^', '^'},
  {'`', '}'}, {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '%') ADVANCE(52);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '<') ADVANCE(73);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '>') ADVANCE(77);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '~') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '~') ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '>') ADVANCE(76);
      if (lookahead != 0) ADVANCE(75);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '+') ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(60);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '*') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '/') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '_') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '@') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '@') ADVANCE(17);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(74);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(61);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '@') ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead == '@') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '[') ADVANCE(67);
      if (lookahead == ']') ADVANCE(68);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(80);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(47);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '+') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '_') ADVANCE(43);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(32);
      END_STATE();
    case 33:
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      if (lookahead == '\n') SKIP(34);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '<') ADVANCE(73);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == ']') ADVANCE(24);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '~') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '\n') SKIP(35);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '+') ADVANCE(48);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '<') ADVANCE(73);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == '@') ADVANCE(22);
      if (lookahead == '[') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(78);
      if (lookahead == ']') ADVANCE(53);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '{') ADVANCE(83);
      if (lookahead == '~') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      if (lookahead != 0) ADVANCE(84);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_bold_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_italic_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_underline_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '_') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_strike_through_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '+') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(65);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_statistics_cookie_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_AT_AT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_export_snippet_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_export_snippet_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_export_snippet_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '<') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT_LT_LT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_regular_link_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK_LBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '@') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(16);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '@') ADVANCE(17);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(17);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_plain_link);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(32);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(59);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_angle_link_token1);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_angle_link_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(62);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_entity_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 10, lookahead))) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 10, lookahead))) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if (lookahead == '}') ADVANCE(81);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 10, lookahead))) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 10, lookahead))) ADVANCE(84);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 34, .external_lex_state = 1},
  [2] = {.lex_state = 34, .external_lex_state = 1},
  [3] = {.lex_state = 34, .external_lex_state = 1},
  [4] = {.lex_state = 35, .external_lex_state = 1},
  [5] = {.lex_state = 34, .external_lex_state = 1},
  [6] = {.lex_state = 34, .external_lex_state = 1},
  [7] = {.lex_state = 34, .external_lex_state = 1},
  [8] = {.lex_state = 34, .external_lex_state = 1},
  [9] = {.lex_state = 34, .external_lex_state = 1},
  [10] = {.lex_state = 34, .external_lex_state = 1},
  [11] = {.lex_state = 34, .external_lex_state = 1},
  [12] = {.lex_state = 34, .external_lex_state = 1},
  [13] = {.lex_state = 34, .external_lex_state = 1},
  [14] = {.lex_state = 34, .external_lex_state = 1},
  [15] = {.lex_state = 34, .external_lex_state = 1},
  [16] = {.lex_state = 34, .external_lex_state = 1},
  [17] = {.lex_state = 34, .external_lex_state = 1},
  [18] = {.lex_state = 34, .external_lex_state = 1},
  [19] = {.lex_state = 34, .external_lex_state = 1},
  [20] = {.lex_state = 34, .external_lex_state = 1},
  [21] = {.lex_state = 34, .external_lex_state = 1},
  [22] = {.lex_state = 0, .external_lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 34},
  [31] = {.lex_state = 35},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 51},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 51},
  [44] = {.lex_state = 35},
  [45] = {.lex_state = 58},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 35},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 34},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 12},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT_AT] = ACTIONS(1),
    [aux_sym_export_snippet_token1] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_entity_token1] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [sym_TAGS] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_inline] = STATE(47),
    [sym_title_with_tags] = STATE(48),
    [sym_title_only] = STATE(49),
    [sym_title] = STATE(22),
    [sym_text_markup] = STATE(3),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_underline] = STATE(6),
    [sym_code] = STATE(6),
    [sym_verbatim] = STATE(6),
    [sym_strike_through] = STATE(6),
    [sym_statistics_cookie] = STATE(3),
    [sym_export_snippet] = STATE(3),
    [sym_target] = STATE(3),
    [sym_radio_target] = STATE(3),
    [sym_regular_link] = STATE(3),
    [sym_angle_link] = STATE(3),
    [sym_entity] = STATE(3),
    [sym_plain_text] = STATE(3),
    [aux_sym_title_repeat1] = STATE(3),
    [anon_sym_COLON] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_AT_AT] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(21),
    [anon_sym_LT_LT_LT] = ACTIONS(23),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(25),
    [sym_plain_link] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(29),
    [aux_sym_plain_text_token1] = ACTIONS(31),
    [sym_TAGS] = ACTIONS(33),
  },
  [STATE(2)] = {
    [sym_text_markup] = STATE(2),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_underline] = STATE(6),
    [sym_code] = STATE(6),
    [sym_verbatim] = STATE(6),
    [sym_strike_through] = STATE(6),
    [sym_statistics_cookie] = STATE(2),
    [sym_export_snippet] = STATE(2),
    [sym_target] = STATE(2),
    [sym_radio_target] = STATE(2),
    [sym_regular_link] = STATE(2),
    [sym_angle_link] = STATE(2),
    [sym_entity] = STATE(2),
    [sym_plain_text] = STATE(2),
    [aux_sym_title_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_COLON] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(40),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym__] = ACTIONS(46),
    [anon_sym_TILDE] = ACTIONS(49),
    [anon_sym_EQ] = ACTIONS(52),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(58),
    [anon_sym_AT_AT] = ACTIONS(61),
    [anon_sym_LT_LT] = ACTIONS(64),
    [anon_sym_LT_LT_LT] = ACTIONS(67),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(70),
    [sym_plain_link] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(73),
    [anon_sym_BSLASH] = ACTIONS(76),
    [aux_sym_plain_text_token1] = ACTIONS(79),
    [sym_TAGS] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym_text_markup] = STATE(2),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [sym_underline] = STATE(6),
    [sym_code] = STATE(6),
    [sym_verbatim] = STATE(6),
    [sym_strike_through] = STATE(6),
    [sym_statistics_cookie] = STATE(2),
    [sym_export_snippet] = STATE(2),
    [sym_target] = STATE(2),
    [sym_radio_target] = STATE(2),
    [sym_regular_link] = STATE(2),
    [sym_angle_link] = STATE(2),
    [sym_entity] = STATE(2),
    [sym_plain_text] = STATE(2),
    [aux_sym_title_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_AT_AT] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(21),
    [anon_sym_LT_LT_LT] = ACTIONS(23),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(25),
    [sym_plain_link] = ACTIONS(84),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(29),
    [aux_sym_plain_text_token1] = ACTIONS(31),
    [sym_TAGS] = ACTIONS(82),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(90), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(88), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(86), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [26] = 2,
    ACTIONS(94), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(92), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [49] = 2,
    ACTIONS(98), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(96), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [72] = 2,
    ACTIONS(102), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(100), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [95] = 2,
    ACTIONS(106), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(104), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [118] = 2,
    ACTIONS(110), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(108), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [141] = 2,
    ACTIONS(114), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(112), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [164] = 2,
    ACTIONS(118), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(116), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [187] = 2,
    ACTIONS(122), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(120), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [210] = 2,
    ACTIONS(126), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(124), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [233] = 2,
    ACTIONS(130), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(128), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [256] = 2,
    ACTIONS(134), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(132), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [279] = 2,
    ACTIONS(138), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(136), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [302] = 2,
    ACTIONS(142), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(140), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [325] = 2,
    ACTIONS(146), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(144), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [348] = 2,
    ACTIONS(150), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(148), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [371] = 2,
    ACTIONS(154), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(152), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [394] = 2,
    ACTIONS(158), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(156), 14,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
  [417] = 2,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 1,
      sym_TAGS,
  [424] = 2,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(166), 1,
      anon_sym_PERCENT,
  [431] = 2,
    ACTIONS(168), 1,
      anon_sym_RBRACK_LBRACK,
    ACTIONS(170), 1,
      anon_sym_RBRACK_RBRACK,
  [438] = 1,
    ACTIONS(172), 1,
      aux_sym_regular_link_token1,
  [442] = 1,
    ACTIONS(174), 1,
      anon_sym_EQ,
  [446] = 1,
    ACTIONS(176), 1,
      anon_sym_PLUS,
  [450] = 1,
    ACTIONS(178), 1,
      aux_sym_code_token1,
  [454] = 1,
    ACTIONS(180), 1,
      anon_sym_COLON,
  [458] = 1,
    ACTIONS(182), 1,
      anon_sym_GT_GT,
  [462] = 1,
    ACTIONS(184), 1,
      anon_sym_GT_GT_GT,
  [466] = 1,
    ACTIONS(186), 1,
      aux_sym_verbatim_token1,
  [470] = 1,
    ACTIONS(188), 1,
      aux_sym_angle_link_token2,
  [474] = 1,
    ACTIONS(190), 1,
      aux_sym_strike_through_token1,
  [478] = 1,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
  [482] = 1,
    ACTIONS(194), 1,
      aux_sym_statistics_cookie_token1,
  [486] = 1,
    ACTIONS(196), 1,
      aux_sym_export_snippet_token1,
  [490] = 1,
    ACTIONS(198), 1,
      aux_sym_target_token1,
  [494] = 1,
    ACTIONS(200), 1,
      aux_sym_target_token1,
  [498] = 1,
    ACTIONS(202), 1,
      aux_sym_regular_link_token1,
  [502] = 1,
    ACTIONS(204), 1,
      anon_sym_TILDE,
  [506] = 1,
    ACTIONS(206), 1,
      aux_sym_entity_token1,
  [510] = 1,
    ACTIONS(208), 1,
      aux_sym_statistics_cookie_token1,
  [514] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
  [518] = 1,
    ACTIONS(212), 1,
      aux_sym_export_snippet_token2,
  [522] = 1,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [526] = 1,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
  [530] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [534] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [538] = 1,
    ACTIONS(222), 1,
      anon_sym_GT,
  [542] = 1,
    ACTIONS(224), 1,
      aux_sym_bold_token1,
  [546] = 1,
    ACTIONS(226), 1,
      anon_sym_RBRACK,
  [550] = 1,
    ACTIONS(228), 1,
      aux_sym_italic_token1,
  [554] = 1,
    ACTIONS(230), 1,
      anon_sym_AT_AT,
  [558] = 1,
    ACTIONS(232), 1,
      anon_sym_RBRACK_RBRACK,
  [562] = 1,
    ACTIONS(234), 1,
      aux_sym_underline_token1,
  [566] = 1,
    ACTIONS(236), 1,
      anon_sym_STAR,
  [570] = 1,
    ACTIONS(238), 1,
      anon_sym_SLASH,
  [574] = 1,
    ACTIONS(240), 1,
      anon_sym__,
  [578] = 1,
    ACTIONS(242), 1,
      aux_sym_angle_link_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 26,
  [SMALL_STATE(6)] = 49,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 95,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 141,
  [SMALL_STATE(11)] = 164,
  [SMALL_STATE(12)] = 187,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 233,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 279,
  [SMALL_STATE(17)] = 302,
  [SMALL_STATE(18)] = 325,
  [SMALL_STATE(19)] = 348,
  [SMALL_STATE(20)] = 371,
  [SMALL_STATE(21)] = 394,
  [SMALL_STATE(22)] = 417,
  [SMALL_STATE(23)] = 424,
  [SMALL_STATE(24)] = 431,
  [SMALL_STATE(25)] = 438,
  [SMALL_STATE(26)] = 442,
  [SMALL_STATE(27)] = 446,
  [SMALL_STATE(28)] = 450,
  [SMALL_STATE(29)] = 454,
  [SMALL_STATE(30)] = 458,
  [SMALL_STATE(31)] = 462,
  [SMALL_STATE(32)] = 466,
  [SMALL_STATE(33)] = 470,
  [SMALL_STATE(34)] = 474,
  [SMALL_STATE(35)] = 478,
  [SMALL_STATE(36)] = 482,
  [SMALL_STATE(37)] = 486,
  [SMALL_STATE(38)] = 490,
  [SMALL_STATE(39)] = 494,
  [SMALL_STATE(40)] = 498,
  [SMALL_STATE(41)] = 502,
  [SMALL_STATE(42)] = 506,
  [SMALL_STATE(43)] = 510,
  [SMALL_STATE(44)] = 514,
  [SMALL_STATE(45)] = 518,
  [SMALL_STATE(46)] = 522,
  [SMALL_STATE(47)] = 526,
  [SMALL_STATE(48)] = 530,
  [SMALL_STATE(49)] = 534,
  [SMALL_STATE(50)] = 538,
  [SMALL_STATE(51)] = 542,
  [SMALL_STATE(52)] = 546,
  [SMALL_STATE(53)] = 550,
  [SMALL_STATE(54)] = 554,
  [SMALL_STATE(55)] = 558,
  [SMALL_STATE(56)] = 562,
  [SMALL_STATE(57)] = 566,
  [SMALL_STATE(58)] = 570,
  [SMALL_STATE(59)] = 574,
  [SMALL_STATE(60)] = 578,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_text, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_markup, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_markup, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underline, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underline, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strike_through, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strike_through, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_radio_target, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_radio_target, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_link, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_link, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statistics_cookie, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statistics_cookie, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_link, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_link, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statistics_cookie, 5, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statistics_cookie, 5, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_snippet, 5, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_snippet, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_link, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_link, 5, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_only, 1, 0, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_with_tags, 2, 0, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_with_tags, 1, 0, 1),
  [216] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 2, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 1, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_TAGS = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_TAGS] = sym_TAGS,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_TAGS] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_org_inline_external_scanner_create(void);
void tree_sitter_org_inline_external_scanner_destroy(void *);
bool tree_sitter_org_inline_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_org_inline_external_scanner_serialize(void *, char *);
void tree_sitter_org_inline_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_org_inline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_org_inline_external_scanner_create,
      tree_sitter_org_inline_external_scanner_destroy,
      tree_sitter_org_inline_external_scanner_scan,
      tree_sitter_org_inline_external_scanner_serialize,
      tree_sitter_org_inline_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
