/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_STAR = 2,
  aux_sym_bold_token1 = 3,
  anon_sym_SLASH = 4,
  aux_sym_italic_token1 = 5,
  anon_sym__ = 6,
  aux_sym_underline_token1 = 7,
  anon_sym_TILDE = 8,
  aux_sym_code_token1 = 9,
  anon_sym_EQ = 10,
  aux_sym_verbatim_token1 = 11,
  anon_sym_PLUS = 12,
  aux_sym_strike_through_token1 = 13,
  anon_sym_LBRACK = 14,
  aux_sym_statistics_cookie_token1 = 15,
  anon_sym_PERCENT = 16,
  anon_sym_RBRACK = 17,
  anon_sym_AT_AT = 18,
  aux_sym_export_snippet_token1 = 19,
  aux_sym_export_snippet_token2 = 20,
  anon_sym_LT_LT = 21,
  aux_sym_target_token1 = 22,
  anon_sym_GT_GT = 23,
  anon_sym_LT_LT_LT = 24,
  anon_sym_GT_GT_GT = 25,
  anon_sym_LBRACK_LBRACK = 26,
  aux_sym_regular_link_token1 = 27,
  anon_sym_RBRACK_LBRACK = 28,
  anon_sym_RBRACK_RBRACK = 29,
  sym_plain_link = 30,
  anon_sym_LT = 31,
  aux_sym_angle_link_token1 = 32,
  aux_sym_angle_link_token2 = 33,
  anon_sym_GT = 34,
  anon_sym_BSLASH = 35,
  aux_sym_entity_token1 = 36,
  anon_sym_LBRACE_RBRACE = 37,
  anon_sym_LBRACE_LBRACE_LBRACE = 38,
  aux_sym_macro_token1 = 39,
  anon_sym_LPAREN = 40,
  aux_sym_macro_token2 = 41,
  anon_sym_RPAREN = 42,
  anon_sym_RBRACE_RBRACE_RBRACE = 43,
  aux_sym_plain_text_token1 = 44,
  sym_TAGS = 45,
  sym_inline = 46,
  sym_title_with_tags = 47,
  sym_title_only = 48,
  sym_title = 49,
  sym_text_markup = 50,
  sym_bold = 51,
  sym_italic = 52,
  sym_underline = 53,
  sym_code = 54,
  sym_verbatim = 55,
  sym_strike_through = 56,
  sym_statistics_cookie = 57,
  sym_export_snippet = 58,
  sym_target = 59,
  sym_radio_target = 60,
  sym_regular_link = 61,
  sym_angle_link = 62,
  sym_entity = 63,
  sym_macro = 64,
  sym_plain_text = 65,
  aux_sym_title_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_STAR] = "*",
  [aux_sym_bold_token1] = "bold_token1",
  [anon_sym_SLASH] = "/",
  [aux_sym_italic_token1] = "italic_token1",
  [anon_sym__] = "_",
  [aux_sym_underline_token1] = "underline_token1",
  [anon_sym_TILDE] = "~",
  [aux_sym_code_token1] = "code_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_verbatim_token1] = "verbatim_token1",
  [anon_sym_PLUS] = "+",
  [aux_sym_strike_through_token1] = "strike_through_token1",
  [anon_sym_LBRACK] = "[",
  [aux_sym_statistics_cookie_token1] = "statistics_cookie_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT_AT] = "@@",
  [aux_sym_export_snippet_token1] = "export_snippet_token1",
  [aux_sym_export_snippet_token2] = "export_snippet_token2",
  [anon_sym_LT_LT] = "<<",
  [aux_sym_target_token1] = "target_token1",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT_LT] = "<<<",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [aux_sym_regular_link_token1] = "regular_link_token1",
  [anon_sym_RBRACK_LBRACK] = "][",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_plain_link] = "plain_link",
  [anon_sym_LT] = "<",
  [aux_sym_angle_link_token1] = "angle_link_token1",
  [aux_sym_angle_link_token2] = "angle_link_token2",
  [anon_sym_GT] = ">",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_entity_token1] = "entity_token1",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_LBRACE_LBRACE_LBRACE] = "{{{",
  [aux_sym_macro_token1] = "macro_name",
  [anon_sym_LPAREN] = "(",
  [aux_sym_macro_token2] = "macro_args",
  [anon_sym_RPAREN] = ")",
  [anon_sym_RBRACE_RBRACE_RBRACE] = "}}}",
  [aux_sym_plain_text_token1] = "plain_text_token1",
  [sym_TAGS] = "tags",
  [sym_inline] = "inline",
  [sym_title_with_tags] = "title_with_tags",
  [sym_title_only] = "title_only",
  [sym_title] = "title",
  [sym_text_markup] = "text_markup",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_underline] = "underline",
  [sym_code] = "code",
  [sym_verbatim] = "verbatim",
  [sym_strike_through] = "strike_through",
  [sym_statistics_cookie] = "statistics_cookie",
  [sym_export_snippet] = "export_snippet",
  [sym_target] = "target",
  [sym_radio_target] = "radio_target",
  [sym_regular_link] = "regular_link",
  [sym_angle_link] = "angle_link",
  [sym_entity] = "entity",
  [sym_macro] = "macro",
  [sym_plain_text] = "plain_text",
  [aux_sym_title_repeat1] = "title_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_bold_token1] = aux_sym_bold_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym_italic_token1] = aux_sym_italic_token1,
  [anon_sym__] = anon_sym__,
  [aux_sym_underline_token1] = aux_sym_underline_token1,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_verbatim_token1] = aux_sym_verbatim_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_strike_through_token1] = aux_sym_strike_through_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_statistics_cookie_token1] = aux_sym_statistics_cookie_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT_AT] = anon_sym_AT_AT,
  [aux_sym_export_snippet_token1] = aux_sym_export_snippet_token1,
  [aux_sym_export_snippet_token2] = aux_sym_export_snippet_token2,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [aux_sym_target_token1] = aux_sym_target_token1,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT_LT] = anon_sym_LT_LT_LT,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [aux_sym_regular_link_token1] = aux_sym_regular_link_token1,
  [anon_sym_RBRACK_LBRACK] = anon_sym_RBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_plain_link] = sym_plain_link,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_angle_link_token1] = aux_sym_angle_link_token1,
  [aux_sym_angle_link_token2] = aux_sym_angle_link_token2,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_entity_token1] = aux_sym_entity_token1,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE_LBRACE,
  [aux_sym_macro_token1] = aux_sym_macro_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_macro_token2] = aux_sym_macro_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_RBRACE_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE_RBRACE,
  [aux_sym_plain_text_token1] = aux_sym_plain_text_token1,
  [sym_TAGS] = sym_TAGS,
  [sym_inline] = sym_inline,
  [sym_title_with_tags] = sym_title_with_tags,
  [sym_title_only] = sym_title_only,
  [sym_title] = sym_title,
  [sym_text_markup] = sym_text_markup,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_underline] = sym_underline,
  [sym_code] = sym_code,
  [sym_verbatim] = sym_verbatim,
  [sym_strike_through] = sym_strike_through,
  [sym_statistics_cookie] = sym_statistics_cookie,
  [sym_export_snippet] = sym_export_snippet,
  [sym_target] = sym_target,
  [sym_radio_target] = sym_radio_target,
  [sym_regular_link] = sym_regular_link,
  [sym_angle_link] = sym_angle_link,
  [sym_entity] = sym_entity,
  [sym_macro] = sym_macro,
  [sym_plain_text] = sym_plain_text,
  [aux_sym_title_repeat1] = aux_sym_title_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bold_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_italic_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_underline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_verbatim_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_strike_through_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_statistics_cookie_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_export_snippet_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_export_snippet_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_target_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_regular_link_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_plain_link] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_angle_link_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_angle_link_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_entity_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_plain_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_TAGS] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_title_with_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_title_only] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_text_markup] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_underline] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_strike_through] = {
    .visible = true,
    .named = true,
  },
  [sym_statistics_cookie] = {
    .visible = true,
    .named = true,
  },
  [sym_export_snippet] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_radio_target] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_link] = {
    .visible = true,
    .named = true,
  },
  [sym_angle_link] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_tags = 1,
  field_title = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_tags] = "tags",
  [field_title] = "title",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tags, 0},
  [1] =
    {field_title, 0},
  [2] =
    {field_tags, 1},
    {field_title, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static const TSCharacterRange aux_sym_plain_text_token1_character_set_1[] = {
  {0, '\t'}, {0x0b, ')'}, {',', '.'}, {'0', '9'}, {';', ';'}, {'?', '?'}, {'A', 'Z'}, {'^', '^'},
  {'`', 'z'}, {'|', '|'}, {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '%') ADVANCE(56);
      if (lookahead == '(') ADVANCE(87);
      if (lookahead == ')') ADVANCE(90);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '+') ADVANCE(52);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == '<') ADVANCE(77);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == '>') ADVANCE(81);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(82);
      if (lookahead == ']') ADVANCE(58);
      if (lookahead == '_') ADVANCE(46);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '~') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '>') ADVANCE(80);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == ']') ADVANCE(57);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '/') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '+') ADVANCE(53);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 11:
      if (lookahead == '\n') SKIP(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '~') ADVANCE(49);
      END_STATE();
    case 12:
      if (lookahead == '\n') SKIP(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '_') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == '\n') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 14:
      if (lookahead == '\n') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '@') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(38);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(78);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(68);
      END_STATE();
    case 22:
      if (lookahead == '>') ADVANCE(65);
      END_STATE();
    case 23:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == '@') ADVANCE(59);
      END_STATE();
    case 25:
      if (lookahead == '@') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(25);
      END_STATE();
    case 26:
      if (lookahead == '[') ADVANCE(71);
      if (lookahead == ']') ADVANCE(72);
      END_STATE();
    case 27:
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(84);
      END_STATE();
    case 28:
      if (lookahead == '{') ADVANCE(85);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(91);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(45);
      END_STATE();
    case 33:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '+') ADVANCE(53);
      END_STATE();
    case 34:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '_') ADVANCE(47);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(37);
      END_STATE();
    case 38:
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(38);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') SKIP(39);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '+') ADVANCE(52);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == '<') ADVANCE(77);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(82);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '_') ADVANCE(46);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '~') ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(93);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_bold_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_italic_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '/') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_underline_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '_') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_strike_through_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '+') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(69);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_statistics_cookie_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(72);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_AT_AT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_export_snippet_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_export_snippet_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_export_snippet_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '<') ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_target_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '>') ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LT_LT_LT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_regular_link_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RBRACK_LBRACK);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '@') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(18);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ':') ADVANCE(38);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_plain_link);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(37);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_plain_link);
      if (lookahead == ')' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(38);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(63);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_angle_link_token1);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_angle_link_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(66);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_entity_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_LBRACE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_macro_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_macro_token2);
      if (lookahead == '\n') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_macro_token2);
      if (lookahead != 0 &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE_RBRACE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 11, lookahead))) ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if ((!eof && set_contains(aux_sym_plain_text_token1_character_set_1, 11, lookahead))) ADVANCE(93);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 39, .external_lex_state = 1},
  [2] = {.lex_state = 39, .external_lex_state = 1},
  [3] = {.lex_state = 39, .external_lex_state = 1},
  [4] = {.lex_state = 39, .external_lex_state = 1},
  [5] = {.lex_state = 39, .external_lex_state = 1},
  [6] = {.lex_state = 39, .external_lex_state = 1},
  [7] = {.lex_state = 39, .external_lex_state = 1},
  [8] = {.lex_state = 39, .external_lex_state = 1},
  [9] = {.lex_state = 39, .external_lex_state = 1},
  [10] = {.lex_state = 39, .external_lex_state = 1},
  [11] = {.lex_state = 39, .external_lex_state = 1},
  [12] = {.lex_state = 39, .external_lex_state = 1},
  [13] = {.lex_state = 39, .external_lex_state = 1},
  [14] = {.lex_state = 39, .external_lex_state = 1},
  [15] = {.lex_state = 39, .external_lex_state = 1},
  [16] = {.lex_state = 39, .external_lex_state = 1},
  [17] = {.lex_state = 39, .external_lex_state = 1},
  [18] = {.lex_state = 39, .external_lex_state = 1},
  [19] = {.lex_state = 39, .external_lex_state = 1},
  [20] = {.lex_state = 39, .external_lex_state = 1},
  [21] = {.lex_state = 39, .external_lex_state = 1},
  [22] = {.lex_state = 39, .external_lex_state = 1},
  [23] = {.lex_state = 39, .external_lex_state = 1},
  [24] = {.lex_state = 0, .external_lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 55},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 62},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 55},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 39},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT_AT] = ACTIONS(1),
    [aux_sym_export_snippet_token1] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_entity_token1] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE_RBRACE] = ACTIONS(1),
    [sym_TAGS] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_inline] = STATE(43),
    [sym_title_with_tags] = STATE(67),
    [sym_title_only] = STATE(48),
    [sym_title] = STATE(24),
    [sym_text_markup] = STATE(2),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_underline] = STATE(9),
    [sym_code] = STATE(9),
    [sym_verbatim] = STATE(9),
    [sym_strike_through] = STATE(9),
    [sym_statistics_cookie] = STATE(2),
    [sym_export_snippet] = STATE(2),
    [sym_target] = STATE(2),
    [sym_radio_target] = STATE(2),
    [sym_regular_link] = STATE(2),
    [sym_angle_link] = STATE(2),
    [sym_entity] = STATE(2),
    [sym_macro] = STATE(2),
    [sym_plain_text] = STATE(2),
    [aux_sym_title_repeat1] = STATE(2),
    [anon_sym_COLON] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_AT_AT] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(21),
    [anon_sym_LT_LT_LT] = ACTIONS(23),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(25),
    [sym_plain_link] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(31),
    [aux_sym_plain_text_token1] = ACTIONS(33),
    [sym_TAGS] = ACTIONS(35),
  },
  [STATE(2)] = {
    [sym_text_markup] = STATE(3),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_underline] = STATE(9),
    [sym_code] = STATE(9),
    [sym_verbatim] = STATE(9),
    [sym_strike_through] = STATE(9),
    [sym_statistics_cookie] = STATE(3),
    [sym_export_snippet] = STATE(3),
    [sym_target] = STATE(3),
    [sym_radio_target] = STATE(3),
    [sym_regular_link] = STATE(3),
    [sym_angle_link] = STATE(3),
    [sym_entity] = STATE(3),
    [sym_macro] = STATE(3),
    [sym_plain_text] = STATE(3),
    [aux_sym_title_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_AT_AT] = ACTIONS(19),
    [anon_sym_LT_LT] = ACTIONS(21),
    [anon_sym_LT_LT_LT] = ACTIONS(23),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(25),
    [sym_plain_link] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_BSLASH] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(31),
    [aux_sym_plain_text_token1] = ACTIONS(33),
    [sym_TAGS] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym_text_markup] = STATE(3),
    [sym_bold] = STATE(9),
    [sym_italic] = STATE(9),
    [sym_underline] = STATE(9),
    [sym_code] = STATE(9),
    [sym_verbatim] = STATE(9),
    [sym_strike_through] = STATE(9),
    [sym_statistics_cookie] = STATE(3),
    [sym_export_snippet] = STATE(3),
    [sym_target] = STATE(3),
    [sym_radio_target] = STATE(3),
    [sym_regular_link] = STATE(3),
    [sym_angle_link] = STATE(3),
    [sym_entity] = STATE(3),
    [sym_macro] = STATE(3),
    [sym_plain_text] = STATE(3),
    [aux_sym_title_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym__] = ACTIONS(52),
    [anon_sym_TILDE] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(58),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(64),
    [anon_sym_AT_AT] = ACTIONS(67),
    [anon_sym_LT_LT] = ACTIONS(70),
    [anon_sym_LT_LT_LT] = ACTIONS(73),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(76),
    [sym_plain_link] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_BSLASH] = ACTIONS(82),
    [anon_sym_LBRACE_LBRACE_LBRACE] = ACTIONS(85),
    [aux_sym_plain_text_token1] = ACTIONS(88),
    [sym_TAGS] = ACTIONS(41),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(95), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(93), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(91), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [27] = 2,
    ACTIONS(99), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(97), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [51] = 2,
    ACTIONS(103), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(101), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [75] = 2,
    ACTIONS(107), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(105), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [99] = 2,
    ACTIONS(111), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(109), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [123] = 2,
    ACTIONS(115), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(113), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [147] = 2,
    ACTIONS(119), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(117), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [171] = 2,
    ACTIONS(123), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(121), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [195] = 2,
    ACTIONS(127), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(125), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [219] = 2,
    ACTIONS(131), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(129), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [243] = 2,
    ACTIONS(135), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(133), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [267] = 2,
    ACTIONS(139), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(137), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [291] = 2,
    ACTIONS(143), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(141), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [315] = 2,
    ACTIONS(147), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(145), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [339] = 2,
    ACTIONS(151), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(149), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [363] = 2,
    ACTIONS(155), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(153), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [387] = 2,
    ACTIONS(159), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(157), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [411] = 2,
    ACTIONS(163), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(161), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [435] = 2,
    ACTIONS(167), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(165), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [459] = 2,
    ACTIONS(171), 4,
      anon_sym_LBRACK,
      anon_sym_LT_LT,
      anon_sym_LT,
      aux_sym_plain_text_token1,
    ACTIONS(169), 15,
      sym_TAGS,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym__,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_AT_AT,
      anon_sym_LT_LT_LT,
      anon_sym_LBRACK_LBRACK,
      sym_plain_link,
      anon_sym_BSLASH,
      anon_sym_LBRACE_LBRACE_LBRACE,
  [483] = 2,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      sym_TAGS,
  [490] = 2,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [497] = 2,
    ACTIONS(181), 1,
      anon_sym_RBRACK_LBRACK,
    ACTIONS(183), 1,
      anon_sym_RBRACK_RBRACK,
  [504] = 2,
    ACTIONS(185), 1,
      anon_sym_SLASH,
    ACTIONS(187), 1,
      anon_sym_PERCENT,
  [511] = 1,
    ACTIONS(189), 1,
      aux_sym_macro_token2,
  [515] = 1,
    ACTIONS(191), 1,
      aux_sym_target_token1,
  [519] = 1,
    ACTIONS(193), 1,
      anon_sym_COLON,
  [523] = 1,
    ACTIONS(195), 1,
      anon_sym_GT_GT,
  [527] = 1,
    ACTIONS(197), 1,
      anon_sym_GT_GT_GT,
  [531] = 1,
    ACTIONS(199), 1,
      aux_sym_target_token1,
  [535] = 1,
    ACTIONS(201), 1,
      aux_sym_angle_link_token2,
  [539] = 1,
    ACTIONS(203), 1,
      aux_sym_bold_token1,
  [543] = 1,
    ACTIONS(205), 1,
      aux_sym_regular_link_token1,
  [547] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [551] = 1,
    ACTIONS(209), 1,
      aux_sym_italic_token1,
  [555] = 1,
    ACTIONS(211), 1,
      aux_sym_angle_link_token1,
  [559] = 1,
    ACTIONS(213), 1,
      aux_sym_entity_token1,
  [563] = 1,
    ACTIONS(215), 1,
      aux_sym_macro_token1,
  [567] = 1,
    ACTIONS(217), 1,
      aux_sym_strike_through_token1,
  [571] = 1,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
  [575] = 1,
    ACTIONS(221), 1,
      aux_sym_verbatim_token1,
  [579] = 1,
    ACTIONS(223), 1,
      aux_sym_statistics_cookie_token1,
  [583] = 1,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
  [587] = 1,
    ACTIONS(227), 1,
      aux_sym_export_snippet_token2,
  [591] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [595] = 1,
    ACTIONS(231), 1,
      aux_sym_statistics_cookie_token1,
  [599] = 1,
    ACTIONS(233), 1,
      aux_sym_regular_link_token1,
  [603] = 1,
    ACTIONS(235), 1,
      aux_sym_export_snippet_token1,
  [607] = 1,
    ACTIONS(237), 1,
      anon_sym_GT,
  [611] = 1,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [615] = 1,
    ACTIONS(241), 1,
      aux_sym_code_token1,
  [619] = 1,
    ACTIONS(243), 1,
      aux_sym_underline_token1,
  [623] = 1,
    ACTIONS(245), 1,
      anon_sym_RBRACK,
  [627] = 1,
    ACTIONS(247), 1,
      anon_sym_STAR,
  [631] = 1,
    ACTIONS(249), 1,
      anon_sym_AT_AT,
  [635] = 1,
    ACTIONS(251), 1,
      anon_sym_RBRACK_RBRACK,
  [639] = 1,
    ACTIONS(253), 1,
      anon_sym_SLASH,
  [643] = 1,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [647] = 1,
    ACTIONS(257), 1,
      anon_sym__,
  [651] = 1,
    ACTIONS(259), 1,
      anon_sym_TILDE,
  [655] = 1,
    ACTIONS(261), 1,
      anon_sym_EQ,
  [659] = 1,
    ACTIONS(263), 1,
      anon_sym_RBRACE_RBRACE_RBRACE,
  [663] = 1,
    ACTIONS(265), 1,
      anon_sym_PLUS,
  [667] = 1,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 51,
  [SMALL_STATE(7)] = 75,
  [SMALL_STATE(8)] = 99,
  [SMALL_STATE(9)] = 123,
  [SMALL_STATE(10)] = 147,
  [SMALL_STATE(11)] = 171,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 219,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 267,
  [SMALL_STATE(16)] = 291,
  [SMALL_STATE(17)] = 315,
  [SMALL_STATE(18)] = 339,
  [SMALL_STATE(19)] = 363,
  [SMALL_STATE(20)] = 387,
  [SMALL_STATE(21)] = 411,
  [SMALL_STATE(22)] = 435,
  [SMALL_STATE(23)] = 459,
  [SMALL_STATE(24)] = 483,
  [SMALL_STATE(25)] = 490,
  [SMALL_STATE(26)] = 497,
  [SMALL_STATE(27)] = 504,
  [SMALL_STATE(28)] = 511,
  [SMALL_STATE(29)] = 515,
  [SMALL_STATE(30)] = 519,
  [SMALL_STATE(31)] = 523,
  [SMALL_STATE(32)] = 527,
  [SMALL_STATE(33)] = 531,
  [SMALL_STATE(34)] = 535,
  [SMALL_STATE(35)] = 539,
  [SMALL_STATE(36)] = 543,
  [SMALL_STATE(37)] = 547,
  [SMALL_STATE(38)] = 551,
  [SMALL_STATE(39)] = 555,
  [SMALL_STATE(40)] = 559,
  [SMALL_STATE(41)] = 563,
  [SMALL_STATE(42)] = 567,
  [SMALL_STATE(43)] = 571,
  [SMALL_STATE(44)] = 575,
  [SMALL_STATE(45)] = 579,
  [SMALL_STATE(46)] = 583,
  [SMALL_STATE(47)] = 587,
  [SMALL_STATE(48)] = 591,
  [SMALL_STATE(49)] = 595,
  [SMALL_STATE(50)] = 599,
  [SMALL_STATE(51)] = 603,
  [SMALL_STATE(52)] = 607,
  [SMALL_STATE(53)] = 611,
  [SMALL_STATE(54)] = 615,
  [SMALL_STATE(55)] = 619,
  [SMALL_STATE(56)] = 623,
  [SMALL_STATE(57)] = 627,
  [SMALL_STATE(58)] = 631,
  [SMALL_STATE(59)] = 635,
  [SMALL_STATE(60)] = 639,
  [SMALL_STATE(61)] = 643,
  [SMALL_STATE(62)] = 647,
  [SMALL_STATE(63)] = 651,
  [SMALL_STATE(64)] = 655,
  [SMALL_STATE(65)] = 659,
  [SMALL_STATE(66)] = 663,
  [SMALL_STATE(67)] = 667,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 6, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_text, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_markup, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_markup, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underline, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underline, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strike_through, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strike_through, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_target, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_radio_target, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_radio_target, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_link, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_link, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statistics_cookie, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statistics_cookie, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_link, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_link, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statistics_cookie, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statistics_cookie, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_snippet, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_snippet, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_link, 5, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_link, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_only, 1, 0, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_with_tags, 2, 0, 3),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [219] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 1, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_with_tags, 1, 0, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 2, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_TAGS = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_TAGS] = sym_TAGS,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_TAGS] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_org_inline_external_scanner_create(void);
void tree_sitter_org_inline_external_scanner_destroy(void *);
bool tree_sitter_org_inline_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_org_inline_external_scanner_serialize(void *, char *);
void tree_sitter_org_inline_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_org_inline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_org_inline_external_scanner_create,
      tree_sitter_org_inline_external_scanner_destroy,
      tree_sitter_org_inline_external_scanner_scan,
      tree_sitter_org_inline_external_scanner_serialize,
      tree_sitter_org_inline_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
