/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  anon_sym_LF = 2,
  sym_stars = 3,
  sym_keyword = 4,
  sym_priority = 5,
  aux_sym_title_token1 = 6,
  anon_sym_COLON = 7,
  sym_tag = 8,
  aux_sym_block_begin_token1 = 9,
  aux_sym_block_begin_token2 = 10,
  sym_block_type = 11,
  sym_language = 12,
  sym_block_content = 13,
  aux_sym_block_end_token1 = 14,
  anon_sym_PIPE = 15,
  sym_table_cell = 16,
  sym_table_separator = 17,
  aux_sym_comment_token1 = 18,
  anon_sym_COLONPROPERTIES_COLON = 19,
  aux_sym_property_drawer_token1 = 20,
  anon_sym_COLONEND_COLON = 21,
  sym_key = 22,
  aux_sym_paragraph_token1 = 23,
  aux_sym_paragraph_token2 = 24,
  sym_document = 25,
  sym__element = 26,
  sym_headline = 27,
  sym_title = 28,
  sym_tags = 29,
  sym_block = 30,
  sym_block_begin = 31,
  sym_block_end = 32,
  sym_table = 33,
  sym_table_row = 34,
  sym_comment = 35,
  sym_property_drawer = 36,
  sym_property = 37,
  sym_value = 38,
  sym_paragraph = 39,
  aux_sym_document_repeat1 = 40,
  aux_sym_tags_repeat1 = 41,
  aux_sym_table_repeat1 = 42,
  aux_sym_table_row_repeat1 = 43,
  aux_sym_property_drawer_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [anon_sym_LF] = "\n",
  [sym_stars] = "stars",
  [sym_keyword] = "keyword",
  [sym_priority] = "priority",
  [aux_sym_title_token1] = "title_token1",
  [anon_sym_COLON] = ":",
  [sym_tag] = "tag",
  [aux_sym_block_begin_token1] = "block_begin_token1",
  [aux_sym_block_begin_token2] = "block_begin_token2",
  [sym_block_type] = "block_type",
  [sym_language] = "language",
  [sym_block_content] = "block_content",
  [aux_sym_block_end_token1] = "block_end_token1",
  [anon_sym_PIPE] = "|",
  [sym_table_cell] = "table_cell",
  [sym_table_separator] = "table_separator",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_COLONPROPERTIES_COLON] = ":PROPERTIES:",
  [aux_sym_property_drawer_token1] = "property_drawer_token1",
  [anon_sym_COLONEND_COLON] = ":END:",
  [sym_key] = "key",
  [aux_sym_paragraph_token1] = "paragraph_token1",
  [aux_sym_paragraph_token2] = "paragraph_token2",
  [sym_document] = "document",
  [sym__element] = "_element",
  [sym_headline] = "headline",
  [sym_title] = "title",
  [sym_tags] = "tags",
  [sym_block] = "block",
  [sym_block_begin] = "block_begin",
  [sym_block_end] = "block_end",
  [sym_table] = "table",
  [sym_table_row] = "table_row",
  [sym_comment] = "comment",
  [sym_property_drawer] = "property_drawer",
  [sym_property] = "property",
  [sym_value] = "value",
  [sym_paragraph] = "paragraph",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_table_row_repeat1] = "table_row_repeat1",
  [aux_sym_property_drawer_repeat1] = "property_drawer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LF] = anon_sym_LF,
  [sym_stars] = sym_stars,
  [sym_keyword] = sym_keyword,
  [sym_priority] = sym_priority,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_tag] = sym_tag,
  [aux_sym_block_begin_token1] = aux_sym_block_begin_token1,
  [aux_sym_block_begin_token2] = aux_sym_block_begin_token2,
  [sym_block_type] = sym_block_type,
  [sym_language] = sym_language,
  [sym_block_content] = sym_block_content,
  [aux_sym_block_end_token1] = aux_sym_block_end_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_table_cell] = sym_table_cell,
  [sym_table_separator] = sym_table_separator,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_COLONPROPERTIES_COLON] = anon_sym_COLONPROPERTIES_COLON,
  [aux_sym_property_drawer_token1] = aux_sym_property_drawer_token1,
  [anon_sym_COLONEND_COLON] = anon_sym_COLONEND_COLON,
  [sym_key] = sym_key,
  [aux_sym_paragraph_token1] = aux_sym_paragraph_token1,
  [aux_sym_paragraph_token2] = aux_sym_paragraph_token2,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [sym_headline] = sym_headline,
  [sym_title] = sym_title,
  [sym_tags] = sym_tags,
  [sym_block] = sym_block,
  [sym_block_begin] = sym_block_begin,
  [sym_block_end] = sym_block_end,
  [sym_table] = sym_table,
  [sym_table_row] = sym_table_row,
  [sym_comment] = sym_comment,
  [sym_property_drawer] = sym_property_drawer,
  [sym_property] = sym_property,
  [sym_value] = sym_value,
  [sym_paragraph] = sym_paragraph,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_table_row_repeat1] = aux_sym_table_row_repeat1,
  [aux_sym_property_drawer_repeat1] = aux_sym_property_drawer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_stars] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_begin_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_begin_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_block_type] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_end_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_table_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_table_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLONPROPERTIES_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_property_drawer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLONEND_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_paragraph_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_headline] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_row] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_property_drawer] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_drawer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_language = 2,
  field_priority = 3,
  field_tags = 4,
  field_title = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_language] = "language",
  [field_priority] = "priority",
  [field_tags] = "tags",
  [field_title] = "title",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 2},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 3},
  [14] = {.index = 22, .length = 3},
  [15] = {.index = 25, .length = 3},
  [16] = {.index = 28, .length = 3},
  [17] = {.index = 31, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_title, 2},
  [2] =
    {field_tags, 2},
  [3] =
    {field_keyword, 2},
  [4] =
    {field_priority, 2},
  [5] =
    {field_tags, 3},
    {field_title, 2},
  [7] =
    {field_language, 3},
    {field_type, 1},
  [9] =
    {field_keyword, 2},
    {field_title, 4},
  [11] =
    {field_keyword, 2},
    {field_tags, 4},
  [13] =
    {field_priority, 2},
    {field_title, 4},
  [15] =
    {field_priority, 2},
    {field_tags, 4},
  [17] =
    {field_keyword, 2},
    {field_priority, 4},
  [19] =
    {field_keyword, 2},
    {field_tags, 5},
    {field_title, 4},
  [22] =
    {field_priority, 2},
    {field_tags, 5},
    {field_title, 4},
  [25] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_title, 6},
  [28] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_tags, 6},
  [31] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_tags, 7},
    {field_title, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      ADVANCE_MAP(
        '#', 11,
        '*', 57,
        ':', 94,
        'C', 102,
        'D', 120,
        'N', 107,
        'T', 118,
        'W', 103,
        '[', 14,
        '|', 130,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(134);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '|') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(134);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 50,
        ':', 90,
        'C', 65,
        'D', 83,
        'N', 71,
        'T', 82,
        'W', 66,
        '[', 64,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == '[') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ':') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == ':') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == ' ') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(164);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '|') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0) ADVANCE(133);
      END_STATE();
    case 11:
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == '+') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(135);
      if (lookahead == '+') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '#') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == '#') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(126);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 16:
      if (lookahead == '+') ADVANCE(34);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 17:
      if (lookahead == '+') ADVANCE(35);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(93);
      if (lookahead == '|') ADVANCE(129);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(140);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(139);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 22:
      if (lookahead == 'D') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == ']') ADVANCE(60);
      END_STATE();
    case 25:
      if (lookahead == '_') ADVANCE(128);
      END_STATE();
    case 26:
      if (lookahead == '_') ADVANCE(128);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 27:
      if (lookahead == '_') ADVANCE(96);
      END_STATE();
    case 28:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(33);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(26);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 32:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(45);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 33:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 35:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 36:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 38:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 39:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(31);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 40:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 41:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(32);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 42:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 43:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(24);
      END_STATE();
    case 44:
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 45:
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(127);
      END_STATE();
    case 46:
      if (eof) ADVANCE(47);
      if (lookahead == '\n') SKIP(46);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == ':') ADVANCE(151);
      if (lookahead == '|') ADVANCE(130);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0) ADVANCE(163);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(50);
      if (lookahead == 'C') ADVANCE(65);
      if (lookahead == 'D') ADVANCE(83);
      if (lookahead == 'N') ADVANCE(71);
      if (lookahead == 'T') ADVANCE(82);
      if (lookahead == 'W') ADVANCE(66);
      if (lookahead == '[') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '[') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(132);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_stars);
      if (lookahead == '*') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_stars);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_priority);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_title_token1);
      ADVANCE_MAP(
        '\n', 50,
        ':', 90,
        'C', 65,
        'D', 83,
        'N', 71,
        'T', 82,
        'W', 66,
        '[', 64,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ':') ADVANCE(90);
      if (lookahead == '[') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ':') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '#') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'A') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'A') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'C') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'D') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'D') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'G') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'I') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'I') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'L') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'X') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == ']') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_block_begin_token1);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_block_begin_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'A') ADVANCE(115);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'A') ADVANCE(112);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'C') ADVANCE(109);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'D') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'D') ADVANCE(119);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(123);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(105);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'G') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'I') ADVANCE(122);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'I') ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'L') ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(106);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(117);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'T') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'T') ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'X') ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_block_type);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_block_content);
      if (lookahead == '#') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(126);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_block_content);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_block_end_token1);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(133);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_table_separator);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_COLONPROPERTIES_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_property_drawer_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_COLONEND_COLON);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(134);
      if (lookahead == '+') ADVANCE(145);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead == '|') ADVANCE(142);
      if (lookahead != 0) ADVANCE(163);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(134);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead != 0) ADVANCE(163);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ' ') ADVANCE(136);
      if (lookahead == '+') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '#') ADVANCE(143);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == ':') ADVANCE(151);
      if (lookahead == '|') ADVANCE(131);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(163);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '-') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ':') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'I') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'O') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'P') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'P') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'R') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'R') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'S') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'T') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '_') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(163);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_paragraph_token2);
      if (lookahead == '\n') ADVANCE(164);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 46},
  [2] = {.lex_state = 46},
  [3] = {.lex_state = 46},
  [4] = {.lex_state = 46},
  [5] = {.lex_state = 46},
  [6] = {.lex_state = 46},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 46},
  [9] = {.lex_state = 46},
  [10] = {.lex_state = 46},
  [11] = {.lex_state = 46},
  [12] = {.lex_state = 46},
  [13] = {.lex_state = 46},
  [14] = {.lex_state = 46},
  [15] = {.lex_state = 46},
  [16] = {.lex_state = 46},
  [17] = {.lex_state = 46},
  [18] = {.lex_state = 46},
  [19] = {.lex_state = 46},
  [20] = {.lex_state = 46},
  [21] = {.lex_state = 46},
  [22] = {.lex_state = 46},
  [23] = {.lex_state = 46},
  [24] = {.lex_state = 46},
  [25] = {.lex_state = 46},
  [26] = {.lex_state = 46},
  [27] = {.lex_state = 46},
  [28] = {.lex_state = 46},
  [29] = {.lex_state = 46},
  [30] = {.lex_state = 46},
  [31] = {.lex_state = 46},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 19},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 19},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 19},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 99},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 98},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 138},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 21},
  [65] = {.lex_state = 138},
  [66] = {.lex_state = 19},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 13},
  [70] = {.lex_state = 19},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 13},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 99},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 138},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 21},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 99},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 42},
  [91] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_stars] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [aux_sym_block_begin_token1] = ACTIONS(1),
    [sym_block_type] = ACTIONS(1),
    [aux_sym_block_end_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_table_separator] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(67),
    [sym__element] = STATE(2),
    [sym_headline] = STATE(2),
    [sym_block] = STATE(2),
    [sym_block_begin] = STATE(45),
    [sym_table] = STATE(2),
    [sym_table_row] = STATE(4),
    [sym_comment] = STATE(2),
    [sym_property_drawer] = STATE(2),
    [sym_paragraph] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_table_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_stars] = ACTIONS(5),
    [aux_sym_block_begin_token1] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [sym_table_separator] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(13),
    [anon_sym_COLONPROPERTIES_COLON] = ACTIONS(15),
    [aux_sym_paragraph_token1] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_stars,
    ACTIONS(7), 1,
      aux_sym_block_begin_token1,
    ACTIONS(9), 1,
      anon_sym_PIPE,
    ACTIONS(11), 1,
      sym_table_separator,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_COLONPROPERTIES_COLON,
    ACTIONS(17), 1,
      aux_sym_paragraph_token1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_block_begin,
    STATE(4), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    STATE(3), 8,
      sym__element,
      sym_headline,
      sym_block,
      sym_table,
      sym_comment,
      sym_property_drawer,
      sym_paragraph,
      aux_sym_document_repeat1,
  [42] = 11,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_stars,
    ACTIONS(26), 1,
      aux_sym_block_begin_token1,
    ACTIONS(29), 1,
      anon_sym_PIPE,
    ACTIONS(32), 1,
      sym_table_separator,
    ACTIONS(35), 1,
      aux_sym_comment_token1,
    ACTIONS(38), 1,
      anon_sym_COLONPROPERTIES_COLON,
    ACTIONS(41), 1,
      aux_sym_paragraph_token1,
    STATE(45), 1,
      sym_block_begin,
    STATE(4), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    STATE(3), 8,
      sym__element,
      sym_headline,
      sym_block,
      sym_table,
      sym_comment,
      sym_property_drawer,
      sym_paragraph,
      aux_sym_document_repeat1,
  [84] = 5,
    ACTIONS(9), 1,
      anon_sym_PIPE,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_table_separator,
    STATE(5), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(46), 5,
      sym_stars,
      aux_sym_block_begin_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [105] = 5,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_PIPE,
    ACTIONS(57), 1,
      sym_table_separator,
    STATE(5), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(52), 5,
      sym_stars,
      aux_sym_block_begin_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [126] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [139] = 8,
    ACTIONS(64), 1,
      anon_sym_LF,
    ACTIONS(66), 1,
      sym_keyword,
    ACTIONS(68), 1,
      sym_priority,
    ACTIONS(70), 1,
      aux_sym_title_token1,
    ACTIONS(72), 1,
      sym_tag,
    STATE(39), 1,
      sym_title,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(81), 1,
      sym_tags,
  [164] = 2,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [177] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [190] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [203] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [216] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [229] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [242] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [255] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [268] = 2,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [281] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [294] = 2,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [307] = 2,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [320] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [333] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [346] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [359] = 2,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [372] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [385] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [398] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [411] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [424] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [437] = 2,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [450] = 2,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [463] = 2,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(168), 7,
      sym_stars,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [476] = 7,
    ACTIONS(70), 1,
      aux_sym_title_token1,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(170), 1,
      anon_sym_LF,
    ACTIONS(172), 1,
      sym_priority,
    STATE(40), 1,
      sym_title,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(75), 1,
      sym_tags,
  [498] = 6,
    ACTIONS(70), 1,
      aux_sym_title_token1,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(174), 1,
      anon_sym_LF,
    STATE(41), 1,
      sym_title,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(91), 1,
      sym_tags,
  [517] = 6,
    ACTIONS(70), 1,
      aux_sym_title_token1,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(176), 1,
      anon_sym_LF,
    STATE(43), 1,
      sym_title,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(80), 1,
      sym_tags,
  [536] = 3,
    ACTIONS(178), 1,
      anon_sym_COLON,
    ACTIONS(180), 1,
      anon_sym_COLONEND_COLON,
    STATE(37), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [547] = 4,
    ACTIONS(182), 1,
      anon_sym_LF,
    ACTIONS(184), 1,
      anon_sym_PIPE,
    ACTIONS(186), 1,
      sym_table_cell,
    STATE(38), 1,
      aux_sym_table_row_repeat1,
  [560] = 3,
    ACTIONS(188), 1,
      anon_sym_COLON,
    ACTIONS(191), 1,
      anon_sym_COLONEND_COLON,
    STATE(37), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [571] = 4,
    ACTIONS(186), 1,
      sym_table_cell,
    ACTIONS(193), 1,
      anon_sym_LF,
    ACTIONS(195), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_table_row_repeat1,
  [584] = 4,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(197), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(78), 1,
      sym_tags,
  [597] = 4,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(199), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(59), 1,
      sym_tags,
  [610] = 4,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(201), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(73), 1,
      sym_tags,
  [623] = 4,
    ACTIONS(203), 1,
      anon_sym_LF,
    ACTIONS(205), 1,
      anon_sym_PIPE,
    ACTIONS(208), 1,
      sym_table_cell,
    STATE(42), 1,
      aux_sym_table_row_repeat1,
  [636] = 4,
    ACTIONS(72), 1,
      sym_tag,
    ACTIONS(211), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_tags_repeat1,
    STATE(86), 1,
      sym_tags,
  [649] = 3,
    ACTIONS(213), 1,
      anon_sym_COLON,
    ACTIONS(215), 1,
      sym_tag,
    STATE(44), 1,
      aux_sym_tags_repeat1,
  [659] = 3,
    ACTIONS(218), 1,
      sym_block_content,
    ACTIONS(220), 1,
      aux_sym_block_end_token1,
    STATE(26), 1,
      sym_block_end,
  [669] = 3,
    ACTIONS(222), 1,
      anon_sym_COLON,
    ACTIONS(224), 1,
      sym_tag,
    STATE(44), 1,
      aux_sym_tags_repeat1,
  [679] = 2,
    ACTIONS(226), 1,
      anon_sym_COLON,
    STATE(35), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [687] = 1,
    ACTIONS(203), 3,
      anon_sym_LF,
      anon_sym_PIPE,
      sym_table_cell,
  [693] = 2,
    ACTIONS(228), 1,
      sym_block_content,
    ACTIONS(230), 1,
      aux_sym_block_end_token1,
  [700] = 2,
    ACTIONS(232), 1,
      anon_sym_COLON,
    ACTIONS(234), 1,
      anon_sym_COLONEND_COLON,
  [707] = 2,
    ACTIONS(236), 1,
      aux_sym_block_end_token1,
    STATE(12), 1,
      sym_block_end,
  [714] = 2,
    ACTIONS(238), 1,
      aux_sym_block_begin_token2,
    ACTIONS(240), 1,
      sym_block_type,
  [721] = 2,
    ACTIONS(242), 1,
      sym_block_content,
    ACTIONS(244), 1,
      aux_sym_block_end_token1,
  [728] = 2,
    ACTIONS(246), 1,
      anon_sym_SPACE,
    ACTIONS(248), 1,
      anon_sym_LF,
  [735] = 2,
    ACTIONS(250), 1,
      anon_sym_LF,
    ACTIONS(252), 1,
      sym_tag,
  [742] = 2,
    ACTIONS(254), 1,
      sym_block_content,
    ACTIONS(256), 1,
      aux_sym_block_end_token1,
  [749] = 2,
    ACTIONS(258), 1,
      aux_sym_title_token1,
    STATE(89), 1,
      sym_value,
  [756] = 2,
    ACTIONS(260), 1,
      anon_sym_LF,
    ACTIONS(262), 1,
      aux_sym_block_begin_token2,
  [763] = 1,
    ACTIONS(264), 1,
      anon_sym_LF,
  [767] = 1,
    ACTIONS(266), 1,
      anon_sym_LF,
  [771] = 1,
    ACTIONS(268), 1,
      aux_sym_paragraph_token2,
  [775] = 1,
    ACTIONS(270), 1,
      aux_sym_property_drawer_token1,
  [779] = 1,
    ACTIONS(272), 1,
      anon_sym_LF,
  [783] = 1,
    ACTIONS(274), 1,
      anon_sym_COLON,
  [787] = 1,
    ACTIONS(276), 1,
      aux_sym_property_drawer_token1,
  [791] = 1,
    ACTIONS(278), 1,
      anon_sym_PIPE,
  [795] = 1,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
  [799] = 1,
    ACTIONS(282), 1,
      anon_sym_SPACE,
  [803] = 1,
    ACTIONS(284), 1,
      anon_sym_SPACE,
  [807] = 1,
    ACTIONS(286), 1,
      sym_key,
  [811] = 1,
    ACTIONS(288), 1,
      anon_sym_SPACE,
  [815] = 1,
    ACTIONS(290), 1,
      anon_sym_SPACE,
  [819] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [823] = 1,
    ACTIONS(294), 1,
      aux_sym_block_begin_token2,
  [827] = 1,
    ACTIONS(296), 1,
      anon_sym_LF,
  [831] = 1,
    ACTIONS(298), 1,
      aux_sym_property_drawer_token1,
  [835] = 1,
    ACTIONS(300), 1,
      anon_sym_LF,
  [839] = 1,
    ACTIONS(302), 1,
      anon_sym_LF,
  [843] = 1,
    ACTIONS(304), 1,
      anon_sym_LF,
  [847] = 1,
    ACTIONS(306), 1,
      anon_sym_LF,
  [851] = 1,
    ACTIONS(308), 1,
      anon_sym_LF,
  [855] = 1,
    ACTIONS(310), 1,
      anon_sym_LF,
  [859] = 1,
    ACTIONS(312), 1,
      anon_sym_LF,
  [863] = 1,
    ACTIONS(314), 1,
      sym_language,
  [867] = 1,
    ACTIONS(316), 1,
      anon_sym_LF,
  [871] = 1,
    ACTIONS(318), 1,
      anon_sym_LF,
  [875] = 1,
    ACTIONS(320), 1,
      aux_sym_block_begin_token2,
  [879] = 1,
    ACTIONS(322), 1,
      anon_sym_LF,
  [883] = 1,
    ACTIONS(324), 1,
      anon_sym_LF,
  [887] = 1,
    ACTIONS(326), 1,
      sym_block_type,
  [891] = 1,
    ACTIONS(328), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 177,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 203,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 229,
  [SMALL_STATE(14)] = 242,
  [SMALL_STATE(15)] = 255,
  [SMALL_STATE(16)] = 268,
  [SMALL_STATE(17)] = 281,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 307,
  [SMALL_STATE(20)] = 320,
  [SMALL_STATE(21)] = 333,
  [SMALL_STATE(22)] = 346,
  [SMALL_STATE(23)] = 359,
  [SMALL_STATE(24)] = 372,
  [SMALL_STATE(25)] = 385,
  [SMALL_STATE(26)] = 398,
  [SMALL_STATE(27)] = 411,
  [SMALL_STATE(28)] = 424,
  [SMALL_STATE(29)] = 437,
  [SMALL_STATE(30)] = 450,
  [SMALL_STATE(31)] = 463,
  [SMALL_STATE(32)] = 476,
  [SMALL_STATE(33)] = 498,
  [SMALL_STATE(34)] = 517,
  [SMALL_STATE(35)] = 536,
  [SMALL_STATE(36)] = 547,
  [SMALL_STATE(37)] = 560,
  [SMALL_STATE(38)] = 571,
  [SMALL_STATE(39)] = 584,
  [SMALL_STATE(40)] = 597,
  [SMALL_STATE(41)] = 610,
  [SMALL_STATE(42)] = 623,
  [SMALL_STATE(43)] = 636,
  [SMALL_STATE(44)] = 649,
  [SMALL_STATE(45)] = 659,
  [SMALL_STATE(46)] = 669,
  [SMALL_STATE(47)] = 679,
  [SMALL_STATE(48)] = 687,
  [SMALL_STATE(49)] = 693,
  [SMALL_STATE(50)] = 700,
  [SMALL_STATE(51)] = 707,
  [SMALL_STATE(52)] = 714,
  [SMALL_STATE(53)] = 721,
  [SMALL_STATE(54)] = 728,
  [SMALL_STATE(55)] = 735,
  [SMALL_STATE(56)] = 742,
  [SMALL_STATE(57)] = 749,
  [SMALL_STATE(58)] = 756,
  [SMALL_STATE(59)] = 763,
  [SMALL_STATE(60)] = 767,
  [SMALL_STATE(61)] = 771,
  [SMALL_STATE(62)] = 775,
  [SMALL_STATE(63)] = 779,
  [SMALL_STATE(64)] = 783,
  [SMALL_STATE(65)] = 787,
  [SMALL_STATE(66)] = 791,
  [SMALL_STATE(67)] = 795,
  [SMALL_STATE(68)] = 799,
  [SMALL_STATE(69)] = 803,
  [SMALL_STATE(70)] = 807,
  [SMALL_STATE(71)] = 811,
  [SMALL_STATE(72)] = 815,
  [SMALL_STATE(73)] = 819,
  [SMALL_STATE(74)] = 823,
  [SMALL_STATE(75)] = 827,
  [SMALL_STATE(76)] = 831,
  [SMALL_STATE(77)] = 835,
  [SMALL_STATE(78)] = 839,
  [SMALL_STATE(79)] = 843,
  [SMALL_STATE(80)] = 847,
  [SMALL_STATE(81)] = 851,
  [SMALL_STATE(82)] = 855,
  [SMALL_STATE(83)] = 859,
  [SMALL_STATE(84)] = 863,
  [SMALL_STATE(85)] = 867,
  [SMALL_STATE(86)] = 871,
  [SMALL_STATE(87)] = 875,
  [SMALL_STATE(88)] = 879,
  [SMALL_STATE(89)] = 883,
  [SMALL_STATE(90)] = 887,
  [SMALL_STATE(91)] = 891,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 12),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 12),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_row, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_row, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 4, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 4, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 4, 0, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 4, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 4),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 5),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 6),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 14),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 14),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 8),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 8),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 9),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 9),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 10),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 11),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 11),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 13),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 13),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_drawer, 7, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_drawer, 7, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 8, 0, 16),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 8, 0, 16),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 8, 0, 15),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 8, 0, 15),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 9, 0, 17),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 9, 0, 17),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_property_drawer_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_drawer_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 3, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 3, 0, 1),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 6, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 6, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 5, 0, 7),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 5, 0, 7),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 6, 0, 7),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 6, 0, 7),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [280] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_org(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
