/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 20
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  anon_sym_LF = 2,
  sym_stars = 3,
  sym_keyword = 4,
  sym_priority = 5,
  aux_sym_title_token1 = 6,
  anon_sym_COLON = 7,
  sym_tag = 8,
  sym_planning_line = 9,
  aux_sym_block_begin_token1 = 10,
  aux_sym_block_begin_token2 = 11,
  sym_block_type = 12,
  sym_language = 13,
  sym_block_content = 14,
  aux_sym_block_end_token1 = 15,
  anon_sym_PIPE = 16,
  sym_table_cell = 17,
  sym_table_separator = 18,
  aux_sym_directive_token1 = 19,
  aux_sym_directive_token2 = 20,
  sym_name = 21,
  aux_sym_comment_token1 = 22,
  anon_sym_COLONPROPERTIES_COLON = 23,
  aux_sym_property_drawer_token1 = 24,
  anon_sym_COLONEND_COLON = 25,
  sym_key = 26,
  aux_sym_paragraph_token1 = 27,
  aux_sym_paragraph_token2 = 28,
  sym_document = 29,
  sym__element = 30,
  sym_headline = 31,
  sym_title = 32,
  sym_tags = 33,
  sym_block = 34,
  sym_block_begin = 35,
  sym_block_end = 36,
  sym_table = 37,
  sym_table_row = 38,
  sym_directive = 39,
  sym_comment = 40,
  sym_property_drawer = 41,
  sym_property = 42,
  sym_value = 43,
  sym_paragraph = 44,
  aux_sym_document_repeat1 = 45,
  aux_sym_tags_repeat1 = 46,
  aux_sym_table_repeat1 = 47,
  aux_sym_table_row_repeat1 = 48,
  aux_sym_property_drawer_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [anon_sym_LF] = "\n",
  [sym_stars] = "stars",
  [sym_keyword] = "keyword",
  [sym_priority] = "priority",
  [aux_sym_title_token1] = "title_token1",
  [anon_sym_COLON] = ":",
  [sym_tag] = "tag",
  [sym_planning_line] = "planning_line",
  [aux_sym_block_begin_token1] = "block_begin_token1",
  [aux_sym_block_begin_token2] = "block_begin_token2",
  [sym_block_type] = "block_type",
  [sym_language] = "language",
  [sym_block_content] = "block_content",
  [aux_sym_block_end_token1] = "block_end_token1",
  [anon_sym_PIPE] = "|",
  [sym_table_cell] = "table_cell",
  [sym_table_separator] = "table_separator",
  [aux_sym_directive_token1] = "directive_token1",
  [aux_sym_directive_token2] = "directive_token2",
  [sym_name] = "name",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_COLONPROPERTIES_COLON] = ":PROPERTIES:",
  [aux_sym_property_drawer_token1] = "property_drawer_token1",
  [anon_sym_COLONEND_COLON] = ":END:",
  [sym_key] = "key",
  [aux_sym_paragraph_token1] = "paragraph_token1",
  [aux_sym_paragraph_token2] = "paragraph_token2",
  [sym_document] = "document",
  [sym__element] = "_element",
  [sym_headline] = "headline",
  [sym_title] = "title",
  [sym_tags] = "tags",
  [sym_block] = "block",
  [sym_block_begin] = "block_begin",
  [sym_block_end] = "block_end",
  [sym_table] = "table",
  [sym_table_row] = "table_row",
  [sym_directive] = "directive",
  [sym_comment] = "comment",
  [sym_property_drawer] = "property_drawer",
  [sym_property] = "property",
  [sym_value] = "value",
  [sym_paragraph] = "paragraph",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_table_row_repeat1] = "table_row_repeat1",
  [aux_sym_property_drawer_repeat1] = "property_drawer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LF] = anon_sym_LF,
  [sym_stars] = sym_stars,
  [sym_keyword] = sym_keyword,
  [sym_priority] = sym_priority,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_tag] = sym_tag,
  [sym_planning_line] = sym_planning_line,
  [aux_sym_block_begin_token1] = aux_sym_block_begin_token1,
  [aux_sym_block_begin_token2] = aux_sym_block_begin_token2,
  [sym_block_type] = sym_block_type,
  [sym_language] = sym_language,
  [sym_block_content] = sym_block_content,
  [aux_sym_block_end_token1] = aux_sym_block_end_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_table_cell] = sym_table_cell,
  [sym_table_separator] = sym_table_separator,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [aux_sym_directive_token2] = aux_sym_directive_token2,
  [sym_name] = sym_name,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_COLONPROPERTIES_COLON] = anon_sym_COLONPROPERTIES_COLON,
  [aux_sym_property_drawer_token1] = aux_sym_property_drawer_token1,
  [anon_sym_COLONEND_COLON] = anon_sym_COLONEND_COLON,
  [sym_key] = sym_key,
  [aux_sym_paragraph_token1] = aux_sym_paragraph_token1,
  [aux_sym_paragraph_token2] = aux_sym_paragraph_token2,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [sym_headline] = sym_headline,
  [sym_title] = sym_title,
  [sym_tags] = sym_tags,
  [sym_block] = sym_block,
  [sym_block_begin] = sym_block_begin,
  [sym_block_end] = sym_block_end,
  [sym_table] = sym_table,
  [sym_table_row] = sym_table_row,
  [sym_directive] = sym_directive,
  [sym_comment] = sym_comment,
  [sym_property_drawer] = sym_property_drawer,
  [sym_property] = sym_property,
  [sym_value] = sym_value,
  [sym_paragraph] = sym_paragraph,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_table_row_repeat1] = aux_sym_table_row_repeat1,
  [aux_sym_property_drawer_repeat1] = aux_sym_property_drawer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_stars] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_planning_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_begin_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_begin_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_block_type] = {
    .visible = true,
    .named = true,
  },
  [sym_language] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_block_end_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_table_cell] = {
    .visible = true,
    .named = true,
  },
  [sym_table_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLONPROPERTIES_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_property_drawer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLONEND_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_paragraph_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_headline] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_row] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_property_drawer] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_drawer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
  field_language = 2,
  field_priority = 3,
  field_tags = 4,
  field_title = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
  [field_language] = "language",
  [field_priority] = "priority",
  [field_tags] = "tags",
  [field_title] = "title",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [9] = {.index = 9, .length = 2},
  [10] = {.index = 11, .length = 2},
  [11] = {.index = 13, .length = 2},
  [12] = {.index = 15, .length = 2},
  [14] = {.index = 17, .length = 2},
  [15] = {.index = 19, .length = 3},
  [16] = {.index = 22, .length = 3},
  [17] = {.index = 25, .length = 3},
  [18] = {.index = 28, .length = 3},
  [19] = {.index = 31, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 1},
  [1] =
    {field_title, 2},
  [2] =
    {field_tags, 2},
  [3] =
    {field_keyword, 2},
  [4] =
    {field_priority, 2},
  [5] =
    {field_tags, 3},
    {field_title, 2},
  [7] =
    {field_language, 3},
    {field_type, 1},
  [9] =
    {field_keyword, 2},
    {field_title, 4},
  [11] =
    {field_keyword, 2},
    {field_tags, 4},
  [13] =
    {field_priority, 2},
    {field_title, 4},
  [15] =
    {field_priority, 2},
    {field_tags, 4},
  [17] =
    {field_keyword, 2},
    {field_priority, 4},
  [19] =
    {field_keyword, 2},
    {field_tags, 5},
    {field_title, 4},
  [22] =
    {field_priority, 2},
    {field_tags, 5},
    {field_title, 4},
  [25] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_title, 6},
  [28] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_tags, 6},
  [31] =
    {field_keyword, 2},
    {field_priority, 4},
    {field_tags, 7},
    {field_title, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [8] = {
    [3] = sym_value,
  },
  [13] = {
    [4] = sym_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(48);
      ADVANCE_MAP(
        '#', 12,
        '*', 58,
        ':', 96,
        'C', 105,
        'D', 123,
        'N', 110,
        'T', 121,
        'W', 106,
        '[', 14,
        '|', 134,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '|') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 51,
        ':', 92,
        'C', 66,
        'D', 84,
        'N', 72,
        'T', 83,
        'W', 67,
        '[', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead == '[') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == ':') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == ':') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(89);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == ' ') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(196);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '|') ADVANCE(133);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(136);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 12:
      if (lookahead == ' ') ADVANCE(142);
      if (lookahead == '+') ADVANCE(139);
      END_STATE();
    case 13:
      if (lookahead == ' ') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(13);
      END_STATE();
    case 14:
      if (lookahead == '#') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == ':') ADVANCE(95);
      if (lookahead == '|') ADVANCE(133);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(141);
      END_STATE();
    case 16:
      if (lookahead == '#') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(130);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 17:
      if (lookahead == '+') ADVANCE(33);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 18:
      if (lookahead == '+') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == '+') ADVANCE(35);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(146);
      END_STATE();
    case 22:
      if (lookahead == ':') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(147);
      END_STATE();
    case 23:
      if (lookahead == 'D') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'N') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == ']') ADVANCE(61);
      END_STATE();
    case 26:
      if (lookahead == '_') ADVANCE(99);
      END_STATE();
    case 27:
      if (lookahead == '_') ADVANCE(132);
      END_STATE();
    case 28:
      if (lookahead == '_') ADVANCE(132);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 29:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(28);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 30:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(46);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 31:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 34:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 36:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 38:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 39:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 40:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(29);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 41:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(30);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 42:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 43:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 44:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      END_STATE();
    case 45:
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(131);
      END_STATE();
    case 47:
      if (eof) ADVANCE(48);
      if (lookahead == '\n') SKIP(47);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == ':') ADVANCE(179);
      if (lookahead == 'C') ADVANCE(173);
      if (lookahead == 'D') ADVANCE(164);
      if (lookahead == 'S') ADVANCE(160);
      if (lookahead == '|') ADVANCE(134);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(152);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(152);
      if (lookahead != 0) ADVANCE(195);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == 'C') ADVANCE(66);
      if (lookahead == 'D') ADVANCE(84);
      if (lookahead == 'N') ADVANCE(72);
      if (lookahead == 'T') ADVANCE(83);
      if (lookahead == 'W') ADVANCE(67);
      if (lookahead == '[') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '[') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(136);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_stars);
      if (lookahead == '*') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_stars);
      if (lookahead == '*') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_priority);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_title_token1);
      ADVANCE_MAP(
        '\n', 51,
        ':', 92,
        'C', 66,
        'D', 84,
        'N', 72,
        'T', 83,
        'W', 67,
        '[', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead == '[') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == ':') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '#') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'A') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'A') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'C') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'D') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'D') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'G') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'I') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'I') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'L') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'N') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'O') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'X') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(89);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(93);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'E') ADVANCE(24);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '#' ||
          lookahead == '%' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_planning_line);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_block_begin_token1);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_block_begin_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_block_begin_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'A') ADVANCE(118);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'A') ADVANCE(115);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'C') ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'D') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'D') ADVANCE(122);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(126);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(117);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'E') ADVANCE(108);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'G') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'I') ADVANCE(125);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'I') ADVANCE(119);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'L') ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(107);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(114);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'N') ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(109);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'O') ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'T') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'T') ADVANCE(116);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_block_type);
      if (lookahead == 'X') ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_block_type);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_block_type);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_language);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_block_content);
      if (lookahead == '#') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(130);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_block_content);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead != 0) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_block_end_token1);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '-') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead == '\n') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '|') ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_table_cell);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_table_separator);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(141);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_COLONPROPERTIES_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_property_drawer_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_COLONEND_COLON);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '+') ADVANCE(153);
      if (lookahead == '-') ADVANCE(148);
      if (lookahead == '|') ADVANCE(149);
      if (lookahead != 0) ADVANCE(195);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '-') ADVANCE(148);
      if (lookahead != 0) ADVANCE(195);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead != 0) ADVANCE(195);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ' ') ADVANCE(143);
      if (lookahead == '+') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      ADVANCE_MAP(
        '#', 151,
        '*', 59,
        ':', 179,
        'C', 173,
        'D', 164,
        'S', 160,
        '|', 135,
        '\t', 152,
        ' ', 152,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(195);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '-') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ':') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ':') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '<') ADVANCE(157);
      if (lookahead == '[') ADVANCE(187);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '>') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(158);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '>') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'A') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'C') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'D') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'D') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'D') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'H') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'I') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'I') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'L') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'L') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'L') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'N') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'O') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'O') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'P') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'P') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'R') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'R') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'S') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'S') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'T') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'U') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ']') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == ']') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '_') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(aux_sym_paragraph_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(aux_sym_paragraph_token2);
      if (lookahead == '\n') ADVANCE(196);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 47},
  [2] = {.lex_state = 47},
  [3] = {.lex_state = 47},
  [4] = {.lex_state = 47},
  [5] = {.lex_state = 47},
  [6] = {.lex_state = 47},
  [7] = {.lex_state = 47},
  [8] = {.lex_state = 47},
  [9] = {.lex_state = 47},
  [10] = {.lex_state = 47},
  [11] = {.lex_state = 47},
  [12] = {.lex_state = 47},
  [13] = {.lex_state = 47},
  [14] = {.lex_state = 47},
  [15] = {.lex_state = 47},
  [16] = {.lex_state = 47},
  [17] = {.lex_state = 47},
  [18] = {.lex_state = 47},
  [19] = {.lex_state = 47},
  [20] = {.lex_state = 47},
  [21] = {.lex_state = 47},
  [22] = {.lex_state = 47},
  [23] = {.lex_state = 47},
  [24] = {.lex_state = 47},
  [25] = {.lex_state = 47},
  [26] = {.lex_state = 47},
  [27] = {.lex_state = 47},
  [28] = {.lex_state = 47},
  [29] = {.lex_state = 47},
  [30] = {.lex_state = 47},
  [31] = {.lex_state = 47},
  [32] = {.lex_state = 47},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 15},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 22},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 102},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 101},
  [61] = {.lex_state = 15},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 102},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 145},
  [66] = {.lex_state = 10},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 15},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 22},
  [71] = {.lex_state = 145},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 102},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 13},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 15},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 22},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 145},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 9},
  [88] = {.lex_state = 22},
  [89] = {.lex_state = 42},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 6},
  [92] = {.lex_state = 43},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 13},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 13},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_stars] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [aux_sym_block_begin_token1] = ACTIONS(1),
    [sym_block_type] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_table_separator] = ACTIONS(1),
    [aux_sym_directive_token1] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(77),
    [sym__element] = STATE(2),
    [sym_headline] = STATE(2),
    [sym_block] = STATE(2),
    [sym_block_begin] = STATE(48),
    [sym_table] = STATE(2),
    [sym_table_row] = STATE(4),
    [sym_directive] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_property_drawer] = STATE(2),
    [sym_paragraph] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_table_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_stars] = ACTIONS(5),
    [sym_planning_line] = ACTIONS(7),
    [aux_sym_block_begin_token1] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_table_separator] = ACTIONS(13),
    [aux_sym_directive_token1] = ACTIONS(15),
    [aux_sym_comment_token1] = ACTIONS(17),
    [anon_sym_COLONPROPERTIES_COLON] = ACTIONS(19),
    [aux_sym_paragraph_token1] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      sym_stars,
    ACTIONS(9), 1,
      aux_sym_block_begin_token1,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    ACTIONS(13), 1,
      sym_table_separator,
    ACTIONS(15), 1,
      aux_sym_directive_token1,
    ACTIONS(17), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      anon_sym_COLONPROPERTIES_COLON,
    ACTIONS(21), 1,
      aux_sym_paragraph_token1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_planning_line,
    STATE(48), 1,
      sym_block_begin,
    STATE(4), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    STATE(3), 9,
      sym__element,
      sym_headline,
      sym_block,
      sym_table,
      sym_directive,
      sym_comment,
      sym_property_drawer,
      sym_paragraph,
      aux_sym_document_repeat1,
  [49] = 13,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_stars,
    ACTIONS(32), 1,
      sym_planning_line,
    ACTIONS(35), 1,
      aux_sym_block_begin_token1,
    ACTIONS(38), 1,
      anon_sym_PIPE,
    ACTIONS(41), 1,
      sym_table_separator,
    ACTIONS(44), 1,
      aux_sym_directive_token1,
    ACTIONS(47), 1,
      aux_sym_comment_token1,
    ACTIONS(50), 1,
      anon_sym_COLONPROPERTIES_COLON,
    ACTIONS(53), 1,
      aux_sym_paragraph_token1,
    STATE(48), 1,
      sym_block_begin,
    STATE(4), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    STATE(3), 9,
      sym__element,
      sym_headline,
      sym_block,
      sym_table,
      sym_directive,
      sym_comment,
      sym_property_drawer,
      sym_paragraph,
      aux_sym_document_repeat1,
  [98] = 5,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      sym_table_separator,
    STATE(5), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(58), 7,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [121] = 5,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    ACTIONS(69), 1,
      sym_table_separator,
    STATE(5), 2,
      sym_table_row,
      aux_sym_table_repeat1,
    ACTIONS(64), 7,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [144] = 2,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [159] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [174] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [189] = 2,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [204] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [219] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [234] = 2,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [249] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [264] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [279] = 2,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [294] = 2,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [309] = 2,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [324] = 2,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [339] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [354] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [369] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [384] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [399] = 2,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    ACTIONS(142), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [414] = 2,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [429] = 2,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [444] = 2,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [459] = 2,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [474] = 2,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [489] = 2,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [504] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [519] = 2,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [534] = 2,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 9,
      sym_stars,
      sym_planning_line,
      aux_sym_block_begin_token1,
      anon_sym_PIPE,
      sym_table_separator,
      aux_sym_directive_token1,
      aux_sym_comment_token1,
      anon_sym_COLONPROPERTIES_COLON,
      aux_sym_paragraph_token1,
  [549] = 8,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      sym_keyword,
    ACTIONS(184), 1,
      sym_priority,
    ACTIONS(186), 1,
      aux_sym_title_token1,
    ACTIONS(188), 1,
      sym_tag,
    STATE(42), 1,
      sym_title,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(82), 1,
      sym_tags,
  [574] = 7,
    ACTIONS(186), 1,
      aux_sym_title_token1,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(190), 1,
      anon_sym_LF,
    ACTIONS(192), 1,
      sym_priority,
    STATE(45), 1,
      sym_title,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(98), 1,
      sym_tags,
  [596] = 6,
    ACTIONS(186), 1,
      aux_sym_title_token1,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(38), 1,
      sym_title,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(64), 1,
      sym_tags,
  [615] = 6,
    ACTIONS(186), 1,
      aux_sym_title_token1,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(196), 1,
      anon_sym_LF,
    STATE(44), 1,
      sym_title,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(62), 1,
      sym_tags,
  [634] = 4,
    ACTIONS(198), 1,
      anon_sym_LF,
    ACTIONS(200), 1,
      anon_sym_PIPE,
    ACTIONS(202), 1,
      sym_table_cell,
    STATE(39), 1,
      aux_sym_table_row_repeat1,
  [647] = 4,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(204), 1,
      anon_sym_LF,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(79), 1,
      sym_tags,
  [660] = 4,
    ACTIONS(202), 1,
      sym_table_cell,
    ACTIONS(206), 1,
      anon_sym_LF,
    ACTIONS(208), 1,
      anon_sym_PIPE,
    STATE(40), 1,
      aux_sym_table_row_repeat1,
  [673] = 4,
    ACTIONS(210), 1,
      anon_sym_LF,
    ACTIONS(212), 1,
      anon_sym_PIPE,
    ACTIONS(215), 1,
      sym_table_cell,
    STATE(40), 1,
      aux_sym_table_row_repeat1,
  [686] = 3,
    ACTIONS(218), 1,
      anon_sym_COLON,
    ACTIONS(221), 1,
      anon_sym_COLONEND_COLON,
    STATE(41), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [697] = 4,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(223), 1,
      anon_sym_LF,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(99), 1,
      sym_tags,
  [710] = 3,
    ACTIONS(225), 1,
      anon_sym_COLON,
    ACTIONS(227), 1,
      anon_sym_COLONEND_COLON,
    STATE(41), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [721] = 4,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(229), 1,
      anon_sym_LF,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(93), 1,
      sym_tags,
  [734] = 4,
    ACTIONS(188), 1,
      sym_tag,
    ACTIONS(231), 1,
      anon_sym_LF,
    STATE(49), 1,
      aux_sym_tags_repeat1,
    STATE(76), 1,
      sym_tags,
  [747] = 1,
    ACTIONS(210), 3,
      anon_sym_LF,
      anon_sym_PIPE,
      sym_table_cell,
  [753] = 2,
    ACTIONS(233), 1,
      anon_sym_COLON,
    STATE(43), 2,
      sym_property,
      aux_sym_property_drawer_repeat1,
  [761] = 3,
    ACTIONS(235), 1,
      sym_block_content,
    ACTIONS(237), 1,
      aux_sym_block_end_token1,
    STATE(27), 1,
      sym_block_end,
  [771] = 3,
    ACTIONS(239), 1,
      anon_sym_COLON,
    ACTIONS(241), 1,
      sym_tag,
    STATE(50), 1,
      aux_sym_tags_repeat1,
  [781] = 3,
    ACTIONS(243), 1,
      anon_sym_COLON,
    ACTIONS(245), 1,
      sym_tag,
    STATE(50), 1,
      aux_sym_tags_repeat1,
  [791] = 2,
    ACTIONS(248), 1,
      aux_sym_block_begin_token2,
    ACTIONS(250), 1,
      sym_block_type,
  [798] = 2,
    ACTIONS(252), 1,
      aux_sym_title_token1,
    ACTIONS(254), 1,
      aux_sym_directive_token2,
  [805] = 2,
    ACTIONS(256), 1,
      sym_block_content,
    ACTIONS(258), 1,
      aux_sym_block_end_token1,
  [812] = 2,
    ACTIONS(260), 1,
      anon_sym_SPACE,
    ACTIONS(262), 1,
      anon_sym_LF,
  [819] = 2,
    ACTIONS(264), 1,
      sym_block_content,
    ACTIONS(266), 1,
      aux_sym_block_end_token1,
  [826] = 2,
    ACTIONS(268), 1,
      aux_sym_block_end_token1,
    STATE(12), 1,
      sym_block_end,
  [833] = 2,
    ACTIONS(270), 1,
      aux_sym_title_token1,
    STATE(96), 1,
      sym_value,
  [840] = 2,
    ACTIONS(272), 1,
      anon_sym_LF,
    ACTIONS(274), 1,
      sym_tag,
  [847] = 2,
    ACTIONS(276), 1,
      sym_block_content,
    ACTIONS(278), 1,
      aux_sym_block_end_token1,
  [854] = 2,
    ACTIONS(280), 1,
      anon_sym_LF,
    ACTIONS(282), 1,
      aux_sym_block_begin_token2,
  [861] = 2,
    ACTIONS(284), 1,
      anon_sym_COLON,
    ACTIONS(286), 1,
      anon_sym_COLONEND_COLON,
  [868] = 1,
    ACTIONS(288), 1,
      anon_sym_LF,
  [872] = 1,
    ACTIONS(290), 1,
      aux_sym_block_begin_token2,
  [876] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [880] = 1,
    ACTIONS(294), 1,
      aux_sym_property_drawer_token1,
  [884] = 1,
    ACTIONS(296), 1,
      aux_sym_paragraph_token2,
  [888] = 1,
    ACTIONS(298), 1,
      anon_sym_LF,
  [892] = 1,
    ACTIONS(300), 1,
      anon_sym_PIPE,
  [896] = 1,
    ACTIONS(302), 1,
      anon_sym_LF,
  [900] = 1,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [904] = 1,
    ACTIONS(306), 1,
      aux_sym_property_drawer_token1,
  [908] = 1,
    ACTIONS(308), 1,
      anon_sym_LF,
  [912] = 1,
    ACTIONS(310), 1,
      aux_sym_block_begin_token2,
  [916] = 1,
    ACTIONS(312), 1,
      anon_sym_SPACE,
  [920] = 1,
    ACTIONS(314), 1,
      anon_sym_SPACE,
  [924] = 1,
    ACTIONS(316), 1,
      anon_sym_LF,
  [928] = 1,
    ACTIONS(318), 1,
      ts_builtin_sym_end,
  [932] = 1,
    ACTIONS(320), 1,
      sym_name,
  [936] = 1,
    ACTIONS(322), 1,
      anon_sym_LF,
  [940] = 1,
    ACTIONS(324), 1,
      anon_sym_COLON,
  [944] = 1,
    ACTIONS(326), 1,
      anon_sym_LF,
  [948] = 1,
    ACTIONS(328), 1,
      anon_sym_LF,
  [952] = 1,
    ACTIONS(330), 1,
      aux_sym_property_drawer_token1,
  [956] = 1,
    ACTIONS(332), 1,
      anon_sym_LF,
  [960] = 1,
    ACTIONS(334), 1,
      anon_sym_LF,
  [964] = 1,
    ACTIONS(336), 1,
      anon_sym_LF,
  [968] = 1,
    ACTIONS(338), 1,
      aux_sym_title_token1,
  [972] = 1,
    ACTIONS(340), 1,
      sym_key,
  [976] = 1,
    ACTIONS(342), 1,
      sym_language,
  [980] = 1,
    ACTIONS(344), 1,
      anon_sym_LF,
  [984] = 1,
    ACTIONS(346), 1,
      anon_sym_LF,
  [988] = 1,
    ACTIONS(348), 1,
      sym_block_type,
  [992] = 1,
    ACTIONS(350), 1,
      anon_sym_LF,
  [996] = 1,
    ACTIONS(352), 1,
      anon_sym_SPACE,
  [1000] = 1,
    ACTIONS(354), 1,
      anon_sym_LF,
  [1004] = 1,
    ACTIONS(356), 1,
      anon_sym_LF,
  [1008] = 1,
    ACTIONS(358), 1,
      anon_sym_SPACE,
  [1012] = 1,
    ACTIONS(360), 1,
      anon_sym_LF,
  [1016] = 1,
    ACTIONS(362), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 159,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 189,
  [SMALL_STATE(10)] = 204,
  [SMALL_STATE(11)] = 219,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 249,
  [SMALL_STATE(14)] = 264,
  [SMALL_STATE(15)] = 279,
  [SMALL_STATE(16)] = 294,
  [SMALL_STATE(17)] = 309,
  [SMALL_STATE(18)] = 324,
  [SMALL_STATE(19)] = 339,
  [SMALL_STATE(20)] = 354,
  [SMALL_STATE(21)] = 369,
  [SMALL_STATE(22)] = 384,
  [SMALL_STATE(23)] = 399,
  [SMALL_STATE(24)] = 414,
  [SMALL_STATE(25)] = 429,
  [SMALL_STATE(26)] = 444,
  [SMALL_STATE(27)] = 459,
  [SMALL_STATE(28)] = 474,
  [SMALL_STATE(29)] = 489,
  [SMALL_STATE(30)] = 504,
  [SMALL_STATE(31)] = 519,
  [SMALL_STATE(32)] = 534,
  [SMALL_STATE(33)] = 549,
  [SMALL_STATE(34)] = 574,
  [SMALL_STATE(35)] = 596,
  [SMALL_STATE(36)] = 615,
  [SMALL_STATE(37)] = 634,
  [SMALL_STATE(38)] = 647,
  [SMALL_STATE(39)] = 660,
  [SMALL_STATE(40)] = 673,
  [SMALL_STATE(41)] = 686,
  [SMALL_STATE(42)] = 697,
  [SMALL_STATE(43)] = 710,
  [SMALL_STATE(44)] = 721,
  [SMALL_STATE(45)] = 734,
  [SMALL_STATE(46)] = 747,
  [SMALL_STATE(47)] = 753,
  [SMALL_STATE(48)] = 761,
  [SMALL_STATE(49)] = 771,
  [SMALL_STATE(50)] = 781,
  [SMALL_STATE(51)] = 791,
  [SMALL_STATE(52)] = 798,
  [SMALL_STATE(53)] = 805,
  [SMALL_STATE(54)] = 812,
  [SMALL_STATE(55)] = 819,
  [SMALL_STATE(56)] = 826,
  [SMALL_STATE(57)] = 833,
  [SMALL_STATE(58)] = 840,
  [SMALL_STATE(59)] = 847,
  [SMALL_STATE(60)] = 854,
  [SMALL_STATE(61)] = 861,
  [SMALL_STATE(62)] = 868,
  [SMALL_STATE(63)] = 872,
  [SMALL_STATE(64)] = 876,
  [SMALL_STATE(65)] = 880,
  [SMALL_STATE(66)] = 884,
  [SMALL_STATE(67)] = 888,
  [SMALL_STATE(68)] = 892,
  [SMALL_STATE(69)] = 896,
  [SMALL_STATE(70)] = 900,
  [SMALL_STATE(71)] = 904,
  [SMALL_STATE(72)] = 908,
  [SMALL_STATE(73)] = 912,
  [SMALL_STATE(74)] = 916,
  [SMALL_STATE(75)] = 920,
  [SMALL_STATE(76)] = 924,
  [SMALL_STATE(77)] = 928,
  [SMALL_STATE(78)] = 932,
  [SMALL_STATE(79)] = 936,
  [SMALL_STATE(80)] = 940,
  [SMALL_STATE(81)] = 944,
  [SMALL_STATE(82)] = 948,
  [SMALL_STATE(83)] = 952,
  [SMALL_STATE(84)] = 956,
  [SMALL_STATE(85)] = 960,
  [SMALL_STATE(86)] = 964,
  [SMALL_STATE(87)] = 968,
  [SMALL_STATE(88)] = 972,
  [SMALL_STATE(89)] = 976,
  [SMALL_STATE(90)] = 980,
  [SMALL_STATE(91)] = 984,
  [SMALL_STATE(92)] = 988,
  [SMALL_STATE(93)] = 992,
  [SMALL_STATE(94)] = 996,
  [SMALL_STATE(95)] = 1000,
  [SMALL_STATE(96)] = 1004,
  [SMALL_STATE(97)] = 1008,
  [SMALL_STATE(98)] = 1012,
  [SMALL_STATE(99)] = 1016,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 4, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 4, 0, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 5),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 5),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_row, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_row, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_row, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 4, 0, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 4, 0, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 9, 0, 19),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 9, 0, 19),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 4),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 5, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 5, 0, 6),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 5, 0, 8),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 5, 0, 8),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 9),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 9),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 10),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 10),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 11),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 11),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 6, 0, 12),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 6, 0, 12),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 6, 0, 13),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 6, 0, 13),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 14),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 14),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 15),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 15),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 7, 0, 16),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 7, 0, 16),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_drawer, 7, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_drawer, 7, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 8, 0, 17),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 8, 0, 17),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headline, 8, 0, 18),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headline, 8, 0, 18),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_row_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [218] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_property_drawer_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_drawer_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 5, 0, 7),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 5, 0, 7),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 6, 0, 7),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 6, 0, 7),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_begin, 3, 0, 1),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_begin, 3, 0, 1),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 6, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 6, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [318] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_org(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
